-- require("nvim-treesitter.configs").setup {
--   ensure_installed = { "markdown" },
--   highlight = {
--     enable = true,
--     disable = { "latex" },
--     additional_vim_regex_highlighting = { "latex", "markdown" },
--   },
--   --other treesitter settings
-- }
